apiVersion: v2
name: brokkr-agent
description: Brokkr Kubernetes cluster agent
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.29.0-0"

dependencies:
  - name: tekton-pipelines
    version: "0.37.2"
    repository: "https://openfunction.github.io/charts/"
    condition: shipwright.enabled
  - name: shipwright-build
    version: "0.10.0"
    repository: "https://openfunction.github.io/charts/"
    condition: shipwright.enabled
