{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brokkr-broker.fullname" . }}
  labels:
    {{- include "brokkr-broker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_USERNAME: {{ include "brokkr-broker.databaseUsername" . | quote }}
  DATABASE_PASSWORD: {{ include "brokkr-broker.databasePassword" . | quote }}
{{- end }}
