{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) (or .Values.tls.cert .Values.tls.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brokkr-broker.fullname" . }}-tls
  labels:
    {{- include "brokkr-broker.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
{{- end }}
