---
apiVersion: v2
name: brokkr-broker
description: Brokkr control plane broker
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: postgresql
    version: "~18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
