---
name: Helm Chart Tests
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
jobs:
  helm_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [broker, agent]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-build-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-build-

      - name: Docker Compose Cache
        uses: actions/cache@v4
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('.angreal/files/docker-compose.yaml') }}

      - name: Create required directories
        run: |
          mkdir -p /tmp/brokkr-keys
          chmod 777 /tmp/brokkr-keys

      - name: docker compose up
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ".angreal/files/docker-compose.yaml"

      - name: Execute helm chart tests
        run: angreal helm test ${{ matrix.component }} --skip-docker
